version: '2.4'

services:
#  net:

  qaweb:
    build: .
    ports:
      - 8080:8080
    command: supervisord -c /qaweb/configs/supervisord.ini
    networks:
      - backend
    environment:
      - PYTHONASYNCIODEBUG=0
    volumes:
      - ./src/backend:/qaweb/qaweb
      - ./src/configs:/qaweb/configs
      - aiohttp-sockets:/var/lib/aiohttp
#    depends_on:
#      - net

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      - TZ=Europe/Moscow
    networks:
      - backend
    volumes:
      - ./src/configs/nginx.conf:/etc/nginx/nginx.conf
      - aiohttp-sockets:/var/lib/aiohttp
    depends_on:
      - qaweb

networks:
  backend:

volumes:
  aiohttp-sockets: