version: '2.4'

services:
  bertynet:
    build: .
    ports:
      - 8081:8081
      - 8082:8082
    command: supervisord -c /bertynet/configs/supervisord.ini
    networks:
      - backend
    runtime: nvidia
    ipc: host
    environment:
     - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./bertynet:/bertynet/bertynet
      - ./configs:/bertynet/configs

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      - TZ=Europe/Moscow
    networks:
      - backend
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bertynet

networks:
  backend:
