version: '2.4'

services:
  qaweb:
    build: .
    ports:
      - 8080:8080
    command: supervisord -c /qaweb/configs/supervisord.ini
    networks:
      - backend
    environment:
      - PYTHONASYNCIODEBUG=0
      - GAPI_KEY=0
      - GAPI_CX=0
    volumes:
      - ./qaweb:/qaweb/qaweb
      - ./configs:/qaweb/configs
      - aiohttp-sockets:/var/lib/aiohttp

  nginx:
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Moscow
    networks:
      - backend
    volumes:
      - ../frontend:/var/www/seann.ru
      - aiohttp-sockets:/var/lib/aiohttp
    depends_on:
      - qaweb

networks:
  backend:

volumes:
  aiohttp-sockets: