app:
  debug: true
  environment: development

saas:
  url: "https://www.googleapis.com/customsearch/v1?key={}&cx={}&q="
  conn_timeout: 10
  read_timeout: 10

net:
  url: ""
  conn_timeout: 10
  read_timeout: 10
